version: '3'
services:
  app:
    image: g-tchu8257-docker.pkg.coding.net/cms/server/cms-server:0.0.4
    restart: always
    container_name: app
    security_opt:
      - seccomp:unconfined
    ports:
      - 30000:30000
    volumes:
      - ./.env:/app/.env
      - ./static:/app/static
      - ./logs:/app/logs
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - TZ=Asia/Shanghai
    logging:
      driver: 'json-file'
      options:
        max-size: '500m'
    links:
      - mysql

  mysql:
    image: mariadb
    restart: always
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=jsymember30000
      - MYSQL_DATABASE=coffee-member
    command: --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M;
    ports:
      - 33060:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    logging:
      driver: 'json-file'
      options:
        max-size: '500m'
        max-file: '3'
